### ISSUE TITLE
I am using the Android SDK for Agora.io in my application and trying to implement live audio broadcasting.Getting error

### ISSUE THREAD

**Issue by DipGhosh** [AgoraIO/Basic-Audio-Broadcasting#1]
java.lang.ClassCastException: android.support.multidex.MultiDexApplication cannot be cast to com.addemo.mdp.voice_test.AGApplication at com.addemo.mdp.voice_test.ui.BaseActivity.checkSelfPermission(BaseActivity.java:108) at com.addemo.mdp.voice_test.ui.BaseActivity.checkSelfPermissions(BaseActivity.java:85) at com.addemo.mdp.voice_test.ui.BaseActivity.access$000(BaseActivity.java:38) at com.addemo.mdp.voice_test.ui.BaseActivity$2.run(BaseActivity.java:75)

**Comment by guohai** [comment]
@DipGhosh 

Check your source code at `com.addemo.mdp.voice_test.AGApplication`

And maybe you can check this to have a try.
https://stackoverflow.com/questions/35658796/exception-android-support-multidex-multidexapplication-cannot-be-cast-class?answertab=active#tab-top

https://developer.android.com/studio/build/multidex

**Comment by DipGhosh** [comment]
Hi,
I am doing same code as per your demo,but I am facing this issue.I also add this multidex library in grade but still this issues is existed.
Kindly check my code - https://www.dropbox.com/s/lrrq528mdrrt1ay/Voice_test.zip?dl=0

**Comment by DipGhosh** [comment]
@guohai
I have tried according to your provided link but still issues are existed.
Kindly check my source code- https://www.dropbox.com/s/lrrq528mdrrt1ay/Voice_test.zip?dl=0

**Comment by plutoless** [comment]
@DipGhosh is the issue resolved? if you may share the info this may help others
